language: php

php:
  - 7.1

env:
  - VALIDATION=false
  - VALIDATION=true

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - env: VALIDATION=true

cache:
  directories:
    - validation/frameworks

before_script:
  - phpenv config-rm xdebug.ini

script:
  - |
    if [[ $VALIDATION = true ]]; then
      phpunit --testsuite validation
    else
      phpunit --testsuite invariants
      phpunit --testsuite grammar
      phpunit --testsuite api
    fi
